version: "3"

services:
  app:
    build: .
    container_name: iluma-store.ru
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=iluma-store.ru
      - LETSENCRYPT_HOST=iluma-store.ru
      - LETSENCRYPT_EMAIL=qwe@email.com
    networks:
      - web

networks:
  web:
    external: true
