version: "3"

services:
  app:
    build: .
    container_name: iluma-store-app
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=iluma-store.ru,www.iluma-store.ru
      - LETSENCRYPT_HOST=iluma-store.ru,www.iluma-store.ru
      - LETSENCRYPT_EMAIL=parsh@gmail.com
      - REDIRECT_www.iluma-store.ru=iluma-store.ru
    networks:
      - web
    volumes:
      # Монтируем папку с картинками в контейнер
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # Монтируем папку с билдом Next.js (опционально для кэширования)
      # - /var/www/iluma-store.ru/.next:/app/.next

networks:
  web:
    external: true
